# This is a template, please create a copy before changing anything
#
# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-XXXXXXXXXXXXXXXXX

Verbose     : true

BaseDir          : '/lastXX/dataX/archive' # The (existing) directory.
DataDir          : 'new' # The (new) directory where the regular images will be stored.
LogFileDir       : '/lastXX/dataX/archive/log/' # The directory wehere the log files will be stored.

DarkDBDir        : '/lastXX/data/ServiceImages/darkDB' # The directory where "Dark" images will be stored.
FlatDBDir        : '/lastXX/data/ServiceImages/flatDB' # The directory where "Flat" images will be stored.
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : NN
CameraPos        : 'NESW'
TelescopeOffset  : [0.0, 0.0]
