# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-e69896449e35647d5
Verbose     : true

BaseDir          : '/last04/data2/archive'
DataDir          : 'new'
LogFileDir       : '/last04/data1/archive/LAST/log/'

DarkDBDir        : '/last04/data/ServiceImages/darkDB'
FlatDBDir        : '/last04/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 4
CameraPos        : 'NW'
TelescopeOffset  : [-1.1, 1.65]