# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-f25bb143a87518b5b
Verbose     : true

BaseDir          : '/last02w/data1/archive'
DataDir          : 'new'
LogFileDir       : '/last02w/data1/archive/log/'

DarkDBDir        : '/last02w/data/ServiceImages/darkDB'
FlatDBDir        : '/last02w/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 3
CameraPos        : 'SW'
# Based on plate adjustment done on 2022-06-08
#TelescopeOffset  : [-1.11, -1.60]
# Telescopes coaligned on 2022-11-13
TelescopeOffset  : [0, 0]
