# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-58c58d44bc68c77f4

Verbose     : true

BaseDir          : '/last08w/data2/archive'
DataDir          : 'new'
LogFileDir       : '/last08w/data2/archive/log/'

DarkDBDir        : '/last08w/data/ServiceImages/darkDB'
FlatDBDir        : '/last08w/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 4
CameraPos        : 'NW'
#TelescopeOffset  : [-1.1, 1.65]
# Telescopes coaligned on 2022-12-04
#TelescopeOffset  : [0, 0]
TelescopeOffset  : [-1.07, 1.57]
