# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-aa1c6f4fab9d48eab
Verbose     : true

BaseDir          : '/tmp/last01/data1'
DataDir          : 'archive/LAST' 
LogFileDir       : '/tmp/last01/data1/archive/LAST/log/'

DarkDBDir        : '/tmp/last01/data/ServiceImages/darkDB'
FlatDBDir        : '/tmp/last01/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 2
