# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-181451439232b2668

Verbose     : true

BaseDir          : '/last09e/data1/archive' # The (existing) directory.
DataDir          : 'new' # The (new) directory where the regular images will be stored.
LogFileDir       : '/last09e/data1/archive/log/' # The directory wehere the log files will be stored.

DarkDBDir        : '/last09e/data/ServiceImages/darkDB' # The directory where "Dark" images will be stored.
FlatDBDir        : '/last09e/data/ServiceImages/flatDB' # The directory where "Flat" images will be stored.
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 1
CameraPos        : 'NE'
TelescopeOffset  : [1.3, 1.6]

# Keys to be copied verbatim in FITS header (remember to keep the strict
#  format [ [FITSKEY,value],... ] )
ExtraFITSHeader        : [[OPT_CLN,2460992,Last time optics was cleaned, JD]]

