# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-3285554b92e4b97b1
Verbose     : true

BaseDir          : '/last03e/data1/archive'
DataDir          : 'new'
LogFileDir       : '/last03e/data1/archive/log/'

DarkDBDir        : '/last03e/data/ServiceImages/darkDB'
FlatDBDir        : '/last03e/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 1
CameraPos        : 'NE'
TelescopeOffset  : [1.1, 1.65]
