# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-29156a4d9dd8ea1d4

Verbose     : true

BaseDir          : '/last06e/data1/archive' # The (existing) directory.
DataDir          : 'new' # The (new) directory where the regular images will be stored.
LogFileDir       : '/last06e/data1/archive/log/' # The directory wehere the log files will be stored.

DarkDBDir        : '/last06e/data/ServiceImages/darkDB' # The directory where "Dark" images will be stored.
FlatDBDir        : '/last06e/data/ServiceImages/flatDB' # The directory where "Flat" images will be stored.
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 2
CameraPos        : 'SE'
TelescopeOffset  : [0.0, 0.0]
