# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-f66f2d469925fea7b
Verbose     : true

BaseDir          : '/last03/data1'
DataDir          : 'archive/LAST' 
LogFileDir       : '/last03/data1/archive/LAST/log/'

DarkDBDir        : '/last03/data/ServiceImages/darkDB'
FlatDBDir        : '/last03/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 1
CameraPos        : 'NE'
TelescopeOffset  : [1.1, 1.65]