# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-14b54b419653bc47e

Verbose     : true

BaseDir          : '/last01w/data2/archive'
DataDir          : 'new'
LogFileDir       : '/last01w/data2/archive/log/'

DarkDBDir        : '/last01w/data/ServiceImages/darkDB'
FlatDBDir        : '/last01w/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 4
CameraPos        : 'NW'
#TelescopeOffset  : [0.0, 0.0]
TelescopeOffset  : [-0.89, 1.43]
