# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-a51e1c41b5d4b48f7
Verbose     : true

BaseDir          : '/last01w/data1/archive'
DataDir          : 'new'
LogFileDir       : '/last01w/data1/archive/log/'

DarkDBDir        : '/last01w/data/ServiceImages/darkDB'
FlatDBDir        : '/last01w/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 3
CameraPos        : 'SW'
TelescopeOffset  : [-1.1, -1.65]