# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-51a1fd4485a353a51
Verbose     : true

BaseDir          : '/last03e/data2/archive'
DataDir          : 'new'
LogFileDir       : '/last03e/data2/archive/log/'

DarkDBDir        : '/last03e/data/ServiceImages/darkDB'
FlatDBDir        : '/last03e/data/ServiceImages/flatDB'
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 2
CameraPos        : 'SE'
TelescopeOffset  : [0.0, 0.0]
