# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-f66f2d469925fea7b
Verbose     : true

BaseDir          : '/last02e/data1/archive'
DataDir          : 'new'
LogFileDir       : '/last02e/data1/archive/log/'

DarkDBDir        : '/last02e/data/ServiceImages/darkDB'
FlatDBDir        : '/last02e/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 1
CameraPos        : 'NE'
# Based on plate adjustment done on 2022-06-08
#TelescopeOffset  : [1.11, 1.60]
# Telescopes coaligned on 2022-11-13
#TelescopeOffset  : [0, 0]
# Changed to open mode on 2023-05-22
TelescopeOffset  : [1.0, 1.5]
