# differently than other devices, at connect time we look for a specific 
#  hardware Id. Hence PhysicalId is specified at object creation time and not
#  later at connection time.
PhysicalId  : QHY600M-14b54b419653bc47e
Verbose     : true

BaseDir          : '/last01/data2'
DataDir          : 'archive'
LogFileDir       : '/tmp/last01/data1/archive/LAST/log/'

DarkDBDir        : '/tmp/last01/data/ServiceImages/darkDB'
FlatDBDir        : '/tmp/last01/data/ServiceImages/flatDB' 
DarkDB           : 'darkDB.mat'
FlatDB           : 'flatDB.mat'

Filter           : 'clear'

CameraNumber     : 4  # NW
TelescopeOffset  : [0,0]