UnitHosts : ['last01e', 'last02e', 'last03e', 'last04e', 'last05e', 
             'last06e', 'last07e','last08e', 'last09e', 'last10e']

Logging : true
LoggingDir : '~/log'

UnitTerminal: 'silentx' # no visible shell, plotting possible but will die when caller logs out
