# This is a template, please create a copy before changing anything
#
PromptMirrorLock : # true / false

PhysicalAddress : pci-XXXX:XX:XX.X-usb-X:X:X.X # The physical adress where the focuser is connected. Replace X
