PromptMirrorLock :  false

PhysicalAddress : pci-0000:02:00.0-usb-0:2:1.0 # The physical address of the (USB) port to which the focuser is connected.

FocusValT20 : 3.254492e+04
FocusTempDeriv : 19.776

