PhysicalPort    : 'pci-0000:48:00.0-usb-0:4:1.0'

ObsLon          : 35.0407331
ObsLat          : 30.0529838
ObsHeight       : 415.4

# [Az,Alt] limit - nodes points of the interpolation for the limit mask
# Mandatory: first point Az=0, last point Az=360
AzAltLimit      : [[0, 0],  [90, 10], [180, 15], [270, 10],  [360, 0]]
MinAlt          : 15
HALimit         : 120

LogFileDir      : '/last03e/data1/archive/log'
