MountNumber     : 1
MountClass      : inst.XerxesSimulated
MountName       : 'RAD21drive-932187746_DecD21Dual-13182557'
PhysicalPort    : 'pci-0000:03:00.3-usb-0:2:1.0'

# NOTE: also the driver needs geographical coordinates for celestial computations
#       the abstractor writes them to the driver upon create
ObsLon          : 34.81694
ObsLat          : 31.91111
ObsHeight       : 40

# [Az,Alt] limit - nodes points of the interpolation for the limit mask
# Mandatory: first point Az=0, last point Az=360
AzAltLimit      : [[0, 15], [90, 15], [180, 15], [270, 15], [360, 15]]
MinAlt          : 15
HALimit         : 120

MountHostIP    : 'localhost'

LogFileDir      : '/last01/data1/archive/LAST/log'
