PhysicalPort    : 'pci-0000:48:00.0-usb-0:4:1.0'

ObsLon          : 34.81694
ObsLat          : 31.91111
ObsHeight       : 40

# [Az,Alt] limit - nodes points of the interpolation for the limit mask
# Mandatory: first point Az=0, last point Az=360
AzAltLimit      : [[0, 0],  [90, 10], [180, 15], [270, 10],  [360, 0]]
MinAlt          : 15
HALimit         : 120

LogFileDir      : '/last01/data1/archive/LAST/log'
