ProjectName      : ['LAST']
NodeNumber       : [1]
MountNumber      : [1]
CameraNumber     : [1]
CameraPos        : ['NE']
CameraName       : ['QHY600M-9591234bb4884c26c']
MountCameraDist  : [0]
MountCameraPA    : [0]
PhysicalPort     : ['pci-0000:48:00.0-usb-0:1:1.0']

BaseDir          : ['/last01/data1']

DataDir          : ['archive/LAST']  : 
LogFileDir       : ['/last01/data1/archive/LAST/log/']

DarkDBDir        : ['/last01/data/ServiceImages/darkDB']
FlatDBDir        : ['/last01/data/ServiceImages/flatDB'] 
DarkDB           : ['darkDB.mat']
FlatDB           : ['flatDB.mat']
Filter           : ['clear']

CameraMode       : ['highRN']

CameraHostIP    : ['127.0.0.1']
