---
Projects:
- Name: LAST
  ScopesPerMount: 4
  Dialect: last

- Name: WFAST
  ScopesPerMount: 1
  Dialect: ascom

- Name: MAST
  ScopesPerMount: 1
  Dialect: ascom

- Name: LOCAL
  ScopesPerMount: 1
  Dialect: last
