---
Projects:
- Name: LAST
  Nmounts: 12
  ScopesPerMount: 4
  Dialect: last

- Name: WFAST
  Nmounts: 1
  ScopesPerMount: 1
  Dialect: ascom

- Name: MAST
  Nmounts: 18
  ScopesPerMount: 1
  Dialect: ascom

- Name: LOCAL
  Nmounts: 1
  ScopesPerMount: 1
  Dialect: last
