#
# A list of all known nodes
#
Nodes:
- Name: Neot Smadar
  NodeId: 1
  ProjectName: LAST
  Mounts: 12

- Name: Local
  NodeId: 1
  ProjectName: LOCAL
  Mounts: 1

#
# The current node
#
This:
  Name: Neot Smadar
  NodeId: 1
  ProjectName: LAST
  Mounts: 12
