---
#
# This file configures values for obs.api.Locator.DriverClass field
#
# If a specific overwrite exists, it takes precedence.  If not, the respective
#  default is used.
#
# NOTE:
#   The equipment names must be canonical (i.e.: mount, camera, focuser, unit)
#

default:
 mount:     obs.mount
 camera:    obs.camera
 focuser:   obs.focuser
 unit:      obs.unit

#
# Per-host overwrites.  The example below shows, for host last02e:
#  - A specific focuser class
#  - A default focuser class
#  - A default camera class
#  - Other, not specified, equipment types will get their value(s) from
#     the defaults above.
#
# last02e:
#   focuser2: specific.class.for.focuser.2.on.last02e
#   focuser:  default.focuser.class.on.last02e
#   camera:   default.camera.class.on.last02e
#

#
# Entries for the 'LOCAL' project.  This is used for local (on the current host)
#  development of API entities.
#
# NOTE: The LOCAL section should ALWAYS be commented-out when checked-in
#
#
#LOCAL:
# focuser: inst.CelestronFocuser
