---
default:
- mount:
    driver: inst.XerxesMountBinary
- focuser:
    driver: inst.CelestronFocuser
- camera:
    driver: obs.camera
- switch:
    driver: inst.tinycontrolIPpowerSocketNew


focuser:
- id: 1
    driver: obs.focuser
- id: 3
    driver: obs.focuser
