---
#
# This file configures values for obs.api.Locator.DriverClass field
#
# If a specific overwrite exists, it takes precedence.  If not, the respective
#  default is used.
#
# NOTE:
#   The equipment names must be canonical (i.e.: mount, camera, focuser, unit)
#

default:
 mount:     obs.mount
 camera:    inst.QHYccd
 focuser:   inst.CelestronFocuser
 pswitch:   inst.tinycontrolIPpowerSocket
 unit:      obs.unit

#
# Per-host overwrites.  The example below shows, for host last02e:
#  - A specific focuser class
#  - A default focuser class
#  - A default camera class
#  - Other, not specified, equipment types will get their value(s) from
#     the defaults above.
#
# last02e:
#   focuser2: specific.class.for.focuser.2.on.last02e
#   focuser:  default.focuser.class.on.last02e
#   camera:   default.camera.class.on.last02e
#

#
# Entries for the 'LOCAL' project.  This is used for local (on the current host)
#  development of API entities.
#
# NOTES:
#  - The LOCAL section should ALWAYS be commented-out when checked-in
#  - The LOCAL entry actally FAKES a real machine and, as such it MUST
#     fake some more information:
#      NodeId and ProjectName - are taken from config/obs.api.Nodes.yml/This.{NodeId,ProjectName}
#
#      MountId, MountSide - must be supplied in the 'LOCAL' entry below
#
#
#LOCAL:
# focuser: inst.CelestronFocuser
# MountId: 7
# MountSide: e
