HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -822481
DefaultDecZeroPositionTicks : -17759475

HAZeroPositionTicks :   -896947
DecZeroPositionTicks : -17407437

Verbose :  1
