HAMotorirection  : 1
DecMotorDirection : -1

DecZeroPositionTicks :     -9005635 # reading of the Dec encoder at equatorial plane
HAZeroPositionTicks  :      11371178 # reading of the HA encoder on the meridian
DefaultDecZeroPositionTicks : -9005635 # reading of the Dec encoder at equatorial plane
DefaultHAZeroPositionTicks  : 11371178 # reading of the HA encoder on the meridian
