HAMotorDirection  : 1 # +1 or -1
DecMotorDirection : 1 # +1 or -1

DefaultHAZeroPositionTicks  : 0 # reading of the HA encoder on the meridian
DefaultDecZeroPositionTicks : -16777216 # reading of the Dec encoder at equatorial plane

HAZeroPositionTicks  :    574629 # reading of the HA encoder on the meridian
DecZeroPositionTicks : -16502198 # reading of the Dec encoder at equatorial plane

Verbose : 1
