HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -1848166
DefaultDecZeroPositionTicks : -14529572

HAZeroPositionTicks :  -2101697
DecZeroPositionTicks : -14445970

Verbose :  1
