# This is a template, please create a copy before changing anything
HAMotorDirection  : X # 1 or -1
DecMotorDirection : X # 1 or -1

DefaultHAZeroPositionTicks  : X # reading of the HA encoder on the meridian
DefaultDecZeroPositionTicks : X # reading of the Dec encoder at equatorial plane

HAZeroPositionTicks : X # reading of the HA encoder on the meridian
DecZeroPositionTicks : X # reading of the Dec encoder at equatorial plane 

Verbose : X
