HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -932085
DefaultDecZeroPositionTicks : -20247785

HAZeroPositionTicks :   -591418
DecZeroPositionTicks : -20231411

Verbose :  1
