HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -1848166
DefaultDecZeroPositionTicks : -14529572

HAZeroPositionTicks :  -2053997
DecZeroPositionTicks : -14463266

Verbose :  1
