HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -932085
DefaultDecZeroPositionTicks : -20247785

HAZeroPositionTicks :   -659927
DecZeroPositionTicks : -20285954

Verbose :  1
