HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -822481
DefaultDecZeroPositionTicks : -17759475

HAZeroPositionTicks :   -885206
DecZeroPositionTicks : -17433803

Verbose :  1
