HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -932085
DefaultDecZeroPositionTicks : -20247785

HAZeroPositionTicks :   -663287
DecZeroPositionTicks : -20123194

Verbose :  1
