HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -1848166
DefaultDecZeroPositionTicks : -14529572

HAZeroPositionTicks :  -2065271
DecZeroPositionTicks : -14455346

Verbose :  1
