HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -822481
DefaultDecZeroPositionTicks : -17759475

HAZeroPositionTicks :   -877131
DecZeroPositionTicks : -17442051

Verbose :  1
