HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -822481
DefaultDecZeroPositionTicks : -17759475

HAZeroPositionTicks :   -857960
DecZeroPositionTicks : -17395469

Verbose :  1
