CameraModel       : 'QHY600M-PH'
CameraType        : 'QHY'

ImageSizeXY       : [6387, 9576]
CCDSEC            : [1, 6387, 1, 9576]
SENSSEC           : []     # [xmin xmax ymin ymax] senstive area CCDSEC
OVERSEC           : []     # bias overscan CCDSEC

# measured parameters
Measured_Modes    : [1, 2]
Measured_GainMode : [0, 58]
Measured_RN       : [3.5, 1.5]
Measured_Gain     : [0.77, 0.77]
Measured_DC       : [0.01, 0.01]   # dark current
Measured_Saturation : [60000, 60000]
Measured_NonLin   : [50000, 50000]

# measured parameters
GAIN      : 0.9     # measured Gain [e-/adu]
READNOI   : 1.5
DARKCUR   : 0.01

# camera setting parameters
ReadMode  : 1
CamOffset : 3
CamGain   : 0       # camera gain setting value
Binning   : 1 # problematic [1 1] -> {[1],[1]}


HISTORY : ['']
COMMEMT : ['']