# This is a template, please create a copy before changing anything
#CameraModel       : 'QHY600M-PH'
CameraType        : 'QHY'

ImageSizeXY       : [6422, 9600]
CCDSEC            : [1, 6422, 1, 9600]
SENSSEC           : []     # [xmin xmax ymin ymax] senstive area CCDSEC
OVERSEC           : []     # bias overscan CCDSEC

# measured parameters
Measured_Modes    : [1, 2]
Measured_GainMode : [0, 58]
Measured_RN       : [3.5, 1.5]
Measured_Gain     : [0.77, 0.77]
Measured_DC       : [0.01, 0.01]   # dark current
Measured_Saturation : [60000, 60000]
Measured_NonLin   : [50000, 50000]

# measured parameters
GAIN      : 0.9     # measured Gain [e-/adu]
READNOI   : 1.5
DARKCUR   : 0.01

# camera setting parameters
ReadMode  : 1
Offset : 3
Gain   : 0       # camera gain setting value
Binning: [1, 1]
Temperature : -5


HISTORY : ['']
COMMENT : ['']
