# this is the controller currently on M8
HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -1848166
DefaultDecZeroPositionTicks : -14529572

HAZeroPositionTicks :   2011154
DecZeroPositionTicks : -14301507

Verbose :  1

# increase retries, because communication is problematic
CommandRetries : 4

Acceleration: [9,18]
