# this is the controller currently on M8
HAMotorDirection  : 1
DecMotorDirection : 1

DefaultHAZeroPositionTicks  : -1848166
DefaultDecZeroPositionTicks : -14529572

HAZeroPositionTicks :   1368832
DecZeroPositionTicks : -14717241

Verbose :  1

# increase retries, because communication is problematic
CommandRetries : 4
