ProjName           : 'LAST'
NodeNumber         : 1
TimeZone           : 2   # hours

# how much hardware connected
LocalTelescopes   :  []

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{}' # syntax: {[indices for first slave], [indices for second], ...}

# power switch driver
PowerDriver : [inst.tinycontrolIPpowerSocket,inst.tinycontrolIPpowerSocket] # [] to force to cell

# camera power output assigments 
#  (sad, but yml configuration doesn't allow a more sophysticated structure)
CameraPowerUnit   : [1, 1, 2, 2]
CameraPowerOutput : [1, 2, 5, 6]

# mount driver (for now, a single one)
MountDriver : inst.XerxesMountBinary
MountPowerUnit   : 1
MountPowerOutput : 3

# camera drivers (as many as LocalTelescopes)
CameraDriver : []

# focuser drivers (as many as LocalTelescopes)
FocuserDriver : []

# Keys to be copied verbatim in FITS header (remember to keep the strict
#  format [ ['FITSKEY','value'],... ] )
FITSHeader        : []

