ProjName           : 'LAST'
NodeNumber         : 0 
TimeZone           : 2   # hours

# how much hardware connected
LocalTelescopes   :  [1]
RemoteTelescopes  :  [[3], [4]]  # use syntax [[indices for first slave], [indices for second], ...]

# mount driver (for now 1)
MountDriver : inst.XerxesSimulated

# camera drivers (as many as NumberLocalTelescopes)
CameraDriver : [inst.QHYccd, inst.QHYccd]

# focuser drivers (as many as NumberLocalTelescopes)
FocuserDriver : [inst.CelestronFocuser, inst.CelestronFocuser]
