ProjName           : 'LAST'
NodeNumber         : 0 
TimeZone           : 2   # hours

# how much hardware connected
NumberLocalTelescopes   :  2
NumberRemoteTelescopes  :  0

# focuser drivers (as many as NumberLocalTelescopes)
FocuserDriver : [inst.CelestronFocuser, inst.CelestronFocuser]
