ProjName           : 'LAST'
NodeNumber         : 0
TimeZone           : 2   # hours

# how much hardware connected
LocalTelescopes   :  [1,2]

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{[3,4]}' # syntax: {[indices for first slave], [indices for second], ...}

Id : '0'    # rewrite the Id

# power switch driver
PowerDriver : [inst.tinycontrolIPpowerSocket] # [] to force to cell

# camera power output assigments 
#  (sad, but yml configuration doesn't allow a more sophysticated structure)
CameraPowerUnit   : [1, 1]
CameraPowerOutput : [1, 2]

# mount driver (for now 1)
MountDriver : inst.XerxesSimulated

# camera drivers (as many as LocalTelescopes)
CameraDriver : [inst.QHYccd, inst.QHYccd]

# focuser drivers (as many as LocalTelescopes)
FocuserDriver : [inst.CelestronFocuser, inst.CelestronFocuser]
