# This is a template, please create a copy before changing anything
# When creating the configuration files, there sould be a file for each slave
# unitCS should have 5 configuration files in total: 1 master and 4 slaves

Id : 'X'    # each slave has its uniqe ID

# how much hardware connected
LocalTelescopes   :  [X] # One local telescope (1-4)

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{}' # syntax: {[indices for first slave], [indices for second], ...}

#    slave units need RemoteTelescopes={}, otherwise their initialization tries
#      to open further slaves (failing because of nested callbacks)

# camera drivers (as many as LocalTelescopes)
CameraDriver : ['inst.QHYccd']

# focuser drivers (as many as LocalTelescopes)
FocuserDriver : ['inst.CelestronFocuser']
