ProjName           : 'LAST'
NodeNumber         : 0
TimeZone           : 2   # hours

# how much hardware connected
LocalTelescopes   :  []

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{1,2,3,4}' # syntax: {[indices for first slave], [indices for second], ...}

# power switch driver
PowerDriver : [inst.tinycontrolIPpowerSocket] # [] to force to cell

# camera power output assigments 
#  (sad, but yml configuration doesn't allow a more sophysticated structure)
CameraPowerUnit   : [1, 1, 1, 1]
CameraPowerOutput : [1, 2, 3, 4]

# mount driver (for now, a single one)
MountDriver : inst.XerxesSimulated
MountPowerUnit   : 1
MountPowerOutput : 5

# camera drivers (as many as LocalTelescopes)
CameraDriver : []

# focuser drivers (as many as LocalTelescopes)
FocuserDriver : []
