ProjName           : 'LAST'
NodeNumber         : 0
TimeZone           : 2   # hours

Id : '01'    # rewrite the Id

# how much hardware connected
LocalTelescopes   :  []

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{1,2,3,4}' # syntax: {[indices for first slave], [indices for second], ...}

# power switch driver
PowerDriver : [inst.tinycontrolIPpowerSocket, inst.tinycontrolIPpowerSocket] # [] to force to cell

# camera power output assigments 
#  (sad, but yml configuration doesn't allow a more sophysticated structure)
CameraPowerUnit   : [2, 2, 1, 1]
CameraPowerOutput : [1, 2, 1, 2]

# mount driver (for now 1)
MountDriver : inst.XerxesMount

# camera drivers (as many as LocalTelescopes)
CameraDriver : []

# focuser drivers (as many as LocalTelescopes)
FocuserDriver : []
