MountModel      : ['Xerxes-20']

RA_encoder_direction  : [1]
Dec_encoder_direction : [-1]

DefaultHAZeroPositionTicks  : [11371178] 
DefaultDecZeroPositionTicks : [9005635]

HAZeroPositionTicks :  [11017925]
DecZeroPositionTicks : [9047225]
