ProjName           : 'LAST'
NodeNumber         : 0 
TimeZone           : 2   # hours

# how much hardware connected
LocalTelescopes   :  []

# write the following as string, which will be eval()'d in matlab
RemoteTelescopes  :  '{1,2,3,4}' # syntax: {[indices for first slave], [indices for second], ...}

Id : '0'    # rewrite the Id

# mount driver (for now 1)
MountDriver : inst.XerxesSimulated

# camera drivers (as many as NumberLocalTelescopes)
CameraDriver : []

# focuser drivers (as many as NumberLocalTelescopes)
FocuserDriver : []
